[package]
name = "rtp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.packed_struct]
version = "0.10.1"
features = ["alloc"]
