[package]
name = "robojackets-robocup-rtp"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "Communication Messages for RoboJackets Robocup"
authors = ["Nathaniel Wert <n8.wert.b@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.packed_struct]
version = "0.10.1"
default-features = false

[features]
default = ["std"]
std = ["packed_struct/std"]
nostd = ["packed_struct/alloc"]